[Feat] #4- 마이페이지구현
team-winey/Winey-iOS pull request #20
Opened 2023-07-13 14:44 UTC by GodSamble

## 🔥*Pull requests*

⛳️ **작업한 브랜치**
- feature/#4

👷 **작업한 내용**

마이페이지 뷰 구현

## 🚨참고 사항

iPhone 13 mini (375 x 812)
iPhone 13 Pro (390 x 844)
iPhone SE 2 (385 x 667)
시뮬레이터 기종 변경해도 이상 없습니다 !

## 📸 스크린샷
<img src = "https://github.com/team-winey/Winey-iOS/assets/105866831/62509822-6a40-4ab8-90ab-55661d633fe4" width = "250">

## 📟 관련 이슈
- Resolved: #4

2023-07-13 18:02 UTC, samsung-ga requested changes
고생많았어~~ 🚀

디자인시스템 적용을 가장 먼저 해주면 좋을 듯해~!
그리고 변수명도 조금 더 고민해서 코드 작성하자. 뷰구조를 넣어주면 좋을 거 같아 

코멘트 반영해서 재리뷰 요청 해주세욥

2023-07-13 18:02 UTC, samsung-ga commented on Winey/Winey/Source/Scenes/MyPage/ViewControllers/MypageViewController.swift
> +        default : return .zero
Q) 혹시 다른 기기에서 테스트 해보셨을까유??!! 
이건 우리 아요 최종과제랑 연결되는 부분이라 중요한 부분 같아용 ㅎㅎ 
다른 기기에서 레이아웃이 깨지면 안되니까 이 부분은 테스트해보면 좋겠엉. 적어도 아래 기기는 테스트해보자!!

- iPhone 13 mini (375 x 812)
- iPhone 13 Pro (390 x 844)
- iPhone SE 2 (385 x 667)

2023-07-13 18:02 UTC, samsung-ga requested changes
고생많았어~~ 🚀

디자인시스템 적용을 가장 먼저 해주면 좋을 듯해~!
그리고 변수명도 조금 더 고민해서 코드 작성하자. 뷰구조를 넣어주면 좋을 거 같아 

코멘트 반영해서 재리뷰 요청 해주세욥

2023-07-14 10:13 UTC, GodSamble commented on Winey/Winey/Source/Scenes/MyPage/ViewControllers/MypageViewController.swift
> +    private func setStyle() {
setUI() 로 하기로 했던 컨벤션이 머리를 스치는군요 . . !

2023-07-14 10:35 UTC, GodSamble commented on Winey/Winey/Source/Scenes/MyPage/ViewControllers/MypageViewController.swift
> +            $0.top.equalTo(view.safeAreaInsets)
safeAreaInsets으로 해도 제약조건 거는 것도 가능해! 그치만 찾아본 결과, 안정성있는 safeAreaGuide를 통상적으로 사용한대!

safeAreaGuide 는 세이프에리어 경계선 기반이고,
safeAreaInsets 는 top으로만 해야 레이아웃 잡을 수 있다네.

safeAreaGuide 승 !! 🔴

2023-07-14 10:38 UTC, GodSamble commented on Winey/Winey/Source/Scenes/MyPage/ViewControllers/MypageViewController.swift
> +    }
앞으로 컬렉션뷰나 테이블뷰 스케치할 때, 꼭 고려해야겠다!
안그래도 뷰 계층 잡는 과정에서, Section을 Item으로 인지하고 작성해서 
왜 안되나 한참 고민하고 낭비했는데 스케치 때 진작 고려하면 그럴 일 없겠다! 😄

2023-07-14 14:12 UTC, samsung-ga approved these changes
고생 너무 많았슴다 👍🏻

![image](https://github.com/team-winey/Winey-iOS/assets/56102421/bd14cd19-824c-476c-8848-e95b37efcfbc)

2023-07-14 14:22 UTC, alpha-kwhn commented on Winey/Winey/Source/Scenes/MyPage/Cells/Views/MyfeedCollectionViewCell.swift
> +import SnapKit
P1) 여기도 SnapKit 한 줄 띄워서 적기! 내장 라이브러리 (UIKit)에서 한 칸 띄우고 외부 라이브러리 (SnapKit)을 import 해주어야함

2023-07-14 14:24 UTC, alpha-kwhn approved these changes
잘했다 영민이!! 컨벤션도 금새 다 적응했구만~

2023-07-14 14:33 UTC, merged